### PR TITLE
fix: run ignorefunc on WinEnter

### LINKED ISSUE #7: [Bug] Telescope prompt buffer cannot be ignored
Hi @levouh

This is a really cool plugin/use of window highlights.

Just trying it out and noticed that it seemed to influence my telescope prompt buffer even after adding `Telescope*` to the highlights to ignore and trying to exclude floating windows using
```lua
 if vim.fn.win_gettype(vim.api.nvim_win_get_number(win_id)) ~= '' then return true end

--- and
if vim.api.nvim_win_get_config(window).relative ~= '' then return true end
```

image

(The dark shading in the prompt buffer is the anomaly, it shouldn't be there)

I believe at the time that `WinEnter` and `WinLeave` have been executed, buffer options won't necessarily have been executed yet. I'm not sure how Telescope handles laying out windows, but not particular mixture of blockages/ignoring seems to prevent this window from being affected, I think this may affect some other floating windows but limiting the issue to the easiest to observe for me.

### PR DESCRIPTION
**Pull request by akinsho**
This fixes #7 

@levouh I found that I could fix the interaction between telescope and this plugin by making sure the `ignorefunc` is run when entering a window as well as when leaving it. Not sure why it matters since I don't know the whole flow of the plugin but to my mind if I ignore a window in the ignorefunc this plugin should leave it alone *entirely*

### CODE REVIEW

File: lua/tint.lua [hunk 1]
```diff
@@ -158,6 +158,11 @@ local function verify_version()
 end
 
 __.on_focus = function()
+  local winid = vim.api.nvim_get_current_win()
```
Comment (levouh) [inline lua/tint.lua:161]: Can we pass this through to the function below so we don't end up calling `nvim_get_current_win` twice?

**Comment by levouh** [comment]
This makes sense to me. I'm pretty sure that the issue is actually with some things going on with how the default namespace is being setup (see comments on #11) that I will be looking into today.

Either way though - I agree with what you are noting that the window should be _completely_ left alone if requested.

One small change and then I'm happy to merge this.

**Comment by akinsho** [comment]
Sounds good @levouh. Does

> One small change and then I'm happy to merge this.

Mean a change on my side or yours?

**Comment by levouh** [comment]
> Sounds good @levouh. Does
> 
> > One small change and then I'm happy to merge this.
> 
> Mean a change on my side or yours?

Sorry not used to the mobile interface. I just posted my one comment on your changes.

File: lua/tint.lua (hunk 1 above)
Comment (akinsho) [reply lua/tint.lua:161]: done 👍🏿
